"use client";

import {
  LayoutDashboard,
  FolderKanban,
  Users,
  UserCog,
  Wallet,
  FileText,
  FileSignature,
  Presentation,
  Download,
  Camera,
  LayoutTemplate,
  Settings,
  Bell,
  LogOut,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Plus,
  X,
  Check,
  CheckCircle2,
  Circle,
  Clock,
  Search,
  Filter,
  MoreVertical,
  Pencil,
  Trash2,
  Upload,
  Paperclip,
  MessageSquare,
  Send,
  Eye,
  EyeOff,
  Sun,
  Moon,
  Menu,
  ImageIcon,
  Video,
  FileArchive,
  Link2,
  Mail,
  Phone,
  MapPin,
  Calendar,
  DollarSign,
  TrendingUp,
  TrendingDown,
  AlertCircle,
  Info,
  Copy,
  Share2,
  Building2,
  ShieldCheck,
  UserPlus,
  ArrowRight,
  ArrowLeft,
  User,
  Zap,
  BarChart3,
  Clapperboard,
  CreditCard,
  Receipt,
  Folder,
  HardDrive,
  Command,
  ListChecks,
  Star,
  LayoutGrid,
  Rows3,
  Columns3,
  GanttChartSquare,
  CalendarDays,
  SlidersHorizontal,
  FileUp,
  GripVertical,
  BadgeCheck,
  FileCheck2,
  AlertTriangle,
  Mic,
  Megaphone,
  Home,
  SquarePlay,
  Sparkles,
  Palette,
  Wand2,
  Minus,
  type LucideIcon,
} from "lucide-react";

export const ICONS = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  clients: Users,
  team: UserCog,
  finance: Wallet,
  invoices: FileText,
  contracts: FileSignature,
  proposals: Presentation,
  export: Download,
  equipment: Camera,
  templates: LayoutTemplate,
  settings: Settings,
  bell: Bell,
  logout: LogOut,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  plus: Plus,
  close: X,
  check: Check,
  checkCircle: CheckCircle2,
  circle: Circle,
  clock: Clock,
  search: Search,
  filter: Filter,
  more: MoreVertical,
  edit: Pencil,
  trash: Trash2,
  upload: Upload,
  attachment: Paperclip,
  message: MessageSquare,
  send: Send,
  eye: Eye,
  eyeOff: EyeOff,
  sun: Sun,
  moon: Moon,
  menu: Menu,
  image: ImageIcon,
  video: Video,
  archive: FileArchive,
  link: Link2,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  calendar: Calendar,
  money: DollarSign,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  alert: AlertCircle,
  info: Info,
  copy: Copy,
  share: Share2,
  company: Building2,
  shield: ShieldCheck,
  userPlus: UserPlus,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  user: User,
  zap: Zap,
  barChart: BarChart3,
  episodes: Clapperboard,
  payments: CreditCard,
  expenses: Receipt,
  files: Folder,
  storage: HardDrive,
  command: Command,
  tasks: ListChecks,
  star: Star,
  grid: LayoutGrid,
  list: Rows3,
  kanban: Columns3,
  timeline: GanttChartSquare,
  calendarView: CalendarDays,
  sliders: SlidersHorizontal,
  fileUp: FileUp,
  grip: GripVertical,
  badgeCheck: BadgeCheck,
  fileCheck: FileCheck2,
  warning: AlertTriangle,
  mic: Mic,
  megaphone: Megaphone,
  home: Home,
  youtube: SquarePlay,
  sparkles: Sparkles,
  palette: Palette,
  wand: Wand2,
  minus: Minus,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export default function Icon({
  name,
  size = 18,
  className,
  filled,
}: {
  name: IconName;
  size?: number;
  className?: string;
  filled?: boolean;
}) {
  const Cmp = ICONS[name];
  return <Cmp size={size} className={className} strokeWidth={1.8} fill={filled ? "currentColor" : "none"} />;
}
